seed: 0
exp_name: exp001_train
exp_dir: "checkpoints"

train:
    # Please Specify Your Own Path
    data_dir: "/scratch/liudan/data/onepose"
    # resume_ckpt: "/scratch/liudan/PoseDiffusion/pose_diffusion/outputs/2024-07-26/21-48-27/checkpoints/ckpt_000000"
    # resume_ckpt: "/scratch/liudan/PoseDiffusion/pose_diffusion/outputs/2024-07-29/21-18-06/checkpoints/ckpt_000005"
    # resume_ckpt: "/scratch/liudan/PoseDiffusion/pose_diffusion/outputs/2024-08-06/23-42-06/checkpoints/ckpt_000030"
    resume_ckpt: /scratch/liudan/PoseDiffusion/pose_diffusion/outputs/2024-08-20/23-19-45/checkpoints/ckpt_000000
    
    batch_size: 64
    img_size: 224
    restart_num: 50
    lr: 0.0001
    # resume_ckpt: False
    epochs: 100
    ckpt_interval: 5
    num_workers: 8

    eval_interval: 5

    print_interval: 10

    len_train: 1000
    len_eval: 256

    max_images: 256
    normalize_cameras: False
    persistent_workers: True

    pin_memory: True
    clip_grad: 1.0
    preload_image: False
    cudnnbenchmark: False
    first_camera_transform: True
    min_num_images: 50
    images_per_seq: [3, 51]
    compute_optical: True
    color_aug: True
    erase_aug: False
    batch_repeat: 90

debug: False


MODEL:
    _target_: models.PoseDiffusionModel

    pose_encoding_type: absT_quaR_logFL

    IMAGE_FEATURE_EXTRACTOR: 
        _target_: models.MultiScaleImageFeatureExtractor
        modelname: "dino_vits16"
        freeze: True

    DENOISER: 
        _target_: models.Denoiser
        TRANSFORMER:
            _target_:               models.TransformerEncoderWrapper
            d_model:                512
            nhead:                  4
            dim_feedforward:        1024
            num_encoder_layers:     8
            dropout:                0.1
            batch_first:            True
            norm_first:             True

    DIFFUSER:
        _target_: models.GaussianDiffusion
        beta_schedule: custom
